"""Storage contract. Use cases talk to this Protocol; infra decides how."""

from typing import Protocol


class Repository(Protocol):
    # Messages
    def store_message(self, msg: dict, recipient: str, box: str) -> bool:
        """Store a delivered message. False if the id was already stored."""
        ...

    def messages_in(self, box: str) -> list[dict]:
        """Stored rows for a box, ordered by date. Each row is a dict with
        id, date, sender, payload (the wire message) and in_reply_to."""
        ...

    def find_messages(self, id_prefix: str) -> list[dict]: ...

    def move_sender_to_inbox(self, sender: str) -> None: ...

    def messages_from(self, sender: str) -> list[dict]: ...

    # Contacts
    def is_contact(self, address: str) -> bool: ...

    def add_contact(self, address: str) -> None: ...

    # Outbox (store-and-forward queue)
    def queue_message(self, wire: dict, recipient: str, stamp: str | None) -> None: ...

    def due_outbox(self, now: float) -> list[dict]:
        """Queued entries whose next try is due: id, recipient, payload,
        attempts, stamp."""
        ...

    def all_outbox(self) -> list[dict]: ...

    def delete_outbox(self, message_id: str) -> None: ...

    def bump_outbox(self, message_id: str, next_try: float) -> None: ...

    def replace_outbox_payload(self, message_id: str, wire: dict) -> None: ...

    # Peers (TOFU pins for key continuity)
    def pinned_key(self, address: str) -> str | None: ...

    def pin_key(self, address: str, signing_key: str) -> None: ...

    def unpin_key(self, address: str) -> None: ...

    # Postage stamps
    def add_stamp(self, token: str) -> None: ...

    def consume_stamp(self, token: str) -> bool:
        """Mark an unused stamp as used. False if unknown or already used."""
        ...
